tabs:
  general:
    label: Général
    icon: home
    columns:
      - width: 1/2
        sections:
          home:
            type: pages
            label: Accueil
            layout: cards
            size: huge
            templates:
              - home
            image:
              ratio: 16/9
              cover: true

      - width: 1/2
        sections:
          pages:
            type: pages
            label: Pages
            create: default
            templates:
              - articles
              - notre-histoire
              - qui-sommes-nous
              - contact
              - infos-pratiques
              - default
              - references
              - mentions-legales
              - protection-des-donnees
              - engagement

  seo: tabs/seo-site
